### ISSUE TITLE
Getting panic errors

### ISSUE THREAD

**Issue by phantomwhale** [99designs/aws-ecr-gc#2]
Whilst running the tool over our images in CI, we have started getting the following intermittent errors:

```
running aws-ecr-gc	0s
Total images in workbench-ci (us-east-1): 21
Images to delete (1)
  2017-05-22 05:54:32: sha256:2e1595173... []
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x6df7e4]
 
goroutine 1 [running]:
github.com/99designs/aws-ecr-gc/registry.(*Session).DeleteImages(0xc42000e0a0, 0x7ffdeac09f4a, 0xc, 0xc42025af40, 0x1, 0x1, 0x1, 0x1, 0x711740)
	/home/pda/go/src/github.com/99designs/aws-ecr-gc/registry/ecr.go:76 +0x3b4
main.main()
	/home/pda/go/src/github.com/99designs/aws-ecr-gc/main.go:64 +0x520
```

**Comment by phantomwhale** [comment]
Have a theory that it was my accidental commit to master (not a branch / merged PR) that caused the bug to occur...

**Comment by pda** [comment]
I don't think that should matter… the `aws-ecr-gc` invocation isn't parameterized with anything relating to commit/branch.

**Comment by phantomwhale** [comment]
Makes sense...

But mind you, every commit on a branch was working, and my merged PR to master just worked. So not quite sure what it was, but for now the builds seem to be fixed up again.

Will have a better look tomorrow (and try and recreate properly, if I can). Error seemed to arise from the missing tag at the end of the line - e.g `2017-05-22 05:54:32: sha256:2e1595173... []` instead of `2017-05-22 05:54:32: sha256:2e1595173... [build-abcd1234]`

**Comment by pda** [comment]
This is the source of the last non-error output line and the crashing call: https://github.com/99designs/aws-ecr-gc/blob/master/main.go#L63-L64 … they're both referring to the same `deletionList` and the `printImages()` call shows it's valid.

Here's the line the stack trace says is crashing: https://github.com/99designs/aws-ecr-gc/blob/master/registry/ecr.go#L76
I can't spot a problem between the start of the function and that line.

I'm pretty sure it should handle images without tags. The `BatchDeleteImage` function uses `img.Digest` which is the `sha256:…` value.

Not sure what's happening.

**Comment by phantomwhale** [comment]
Got as far as the `[]` part meaning an "untagged image" - so have removed `--delete-untagged` from our build pipeline, and this seems to be running stable right now.

The weird thing is ever failure to delete an untagged image seems to coincide with that image simply not being there; I wonder if this is a race condition with the script listing an image it wants to delete (which is already in the process of removal, hence no tag) and then the attempt to actually delete failing? 

In any case, I've not seen any random, untagged images getting left behind. Have set myself a note to check in a couple of weeks to see if any cruft is building up, otherwise this seems to be doing the job for us right now.
